spring.application.name=user-service


server.port=8081
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_health
spring.datasource.username=sh_user
spring.datasource.password=sh_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
# secure Base64 key
jwt.secret=V4JHqzO8rJ8J8u1g0tXr2bWkPaZfKkqZjK3HqC7h4A0=
jwt.expiration=3600000
